name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    env:
      node-version: 10.x

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Install Linux Dependencies
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libgnome-keyring-dev icnsutils graphicsmagick rpm bsdtar

    - uses: actions/checkout@v2

    - name: Use Node.js ${{ env.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.node-version }}

    - run: npm ci

    - run: npm test

    - run: npm run dist -- --publish never

    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}
        path: dist
